name: at.teamed.io
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: :year/:month/:day/:title.html

url: http://at.teamed.io

gems:
  - jekyll-sass
  - jekyll-press
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
